name: Traffic to Badge

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Generate traffic badges
        id: traffic
        uses: yi-Xu-0100/traffic-to-badge@v1.4.0
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          static_list: iwallberg-fiuba/TB022---INTRO-DESARROLLO-SOFTWARE
          traffic_branch: traffic

      - name: Deploy traffic badges
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ steps.traffic.outputs.traffic_branch }}
          publish_dir: ${{ steps.traffic.outputs.traffic_path }}
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
